apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: spring-boot-was-liberty-backend-mo-git
spec:
  type: git
  params:
    - name: revision
      value: master
    - name: url
      value: https://github.ibm.com/cpat/spring-boot-was-liberty-backend-mo