apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: build-gitops-pvc-pipeline
spec:
  resources:
    - name: git-source
      type: git
    - name: docker-image
      type: image
  params:
    - name: GITOPS_REPO
      type: string
      default: "https://github.com/matejocovskyibm/spring-boot-was-liberty-backend-gitops-mo.git"
  tasks:
    - name: build
      taskRef:
        name: buildah-pvc-task
        kind: Task
      resources:
        inputs:
          - name: source
            resource: git-source
        outputs:
          - name: source
            resource: git-source
          - name: image
            resource: docker-image
      params:
        - name: TLSVERIFY
          value: "false"
    
    - name: apply-manifests
      taskRef:
        name: apply-manifests-pvc-task
        kind: Task
      resources:
        inputs:
          - name: source
            resource: git-source
            from: [build]
          - name: image
            resource: docker-image
            from: [build]
      runAfter:
        - build

    - name: gitops
      taskRef:
        name: gitops-pvc-task
        kind: Task
      resources:
        inputs:
          - name: source
            resource: git-source
            from: [build]
          - name: image
            resource: docker-image
            from: [build]
      params:
        - name: GITOPS_REPO
          value: $(params.GITOPS_REPO)
      runAfter:
        - apply-manifests
          