apiVersion: v1
items:
- apiVersion: tekton.dev/v1alpha1
  kind: PipelineResource
  metadata:
    name: docker-image
  spec:
    params:
    - name: url
      value: docker-registry.default.svc.cluster.local:5000/spring-boot-liberty-tekton/spring-boot-liberty
    type: image
- apiVersion: tekton.dev/v1alpha1
  kind: PipelineResource
  metadata:
    name: git-source
  spec:
    params:
    - name: revision
      value: master
    - name: url
      value: http://github.com/matejocovskyibm/spring-boot-was-liberty-backend-mo
    type: git
kind: List
