apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: gitops-pvc-task
spec:
  inputs:
    params:
      - name: GITOPS_REPO
        description: The location of the repo to be updated
        default: https://github.com/matejocovskyibm/spring-boot-was-liberty-backend-gitops-mo.git
    resources:
      - type: image
        name: image
      - name: source
        type: git
  steps:
    - name: gitops-step
      image: docker.io/csantanapr/helm-kubectl-curl-git-jq-yq
      workingDir: /workspace/source
      command: ["/bin/bash", "-c"]
      args:
        - |-
          set -e
          SHORT_GIT_HASH=$(cat .git/FETCH_HEAD | awk '{print substr($1,0,7)}')
          NEW_IMAGE=docker-registry.default.svc.cluster.local:5000/spring-boot-liberty-tekton/spring-boot-liberty:$SHORT_GIT_HASH
          echo Setting image to $NEW_IMAGE
          git config --global user.email "tekton@ibmcloud.com"
          git config --global user.name "Tekton Pipeline"
          git clone -b master https://github.com/matejocovskyibm/spring-boot-was-liberty-backend-gitops-mo gitops
          cd gitops/dev
          cp ./deploySpring.template ./deploySpring.yaml
          sed -i "s|<DOCKER_IMAGE>|${NEW_IMAGE}|g" ./deploySpring.yaml
          git add .
          git commit -m "Updating image name"
          git push